# Generated by Django 5.0.5 on 2024-05-16 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCursante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('usuario', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('localidad', models.CharField(blank=True, max_length=50)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('fechaingreso', models.DateField(blank=True, null=True)),
                ('fechaegreso', models.DateField(blank=True, null=True)),
                ('celular', models.CharField(blank=True, max_length=50)),
                ('nrodoc', models.IntegerField(blank=True, default=0)),
                ('casa_practica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='casa_practica', to='bosquetaoista.casa')),
                ('grado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.grado')),
                ('responsable_casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_casa', to='bosquetaoista.casa')),
                ('tipodoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.tipodoc')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.tipoestado')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.evento')),
                ('orador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Cursante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.agenda')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.persona')),
                ('tipocursante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.tipocursante')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.tipoevento'),
        ),
        migrations.CreateModel(
            name='PersonaExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=200)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.persona')),
                ('tipoextra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.tipoextra')),
            ],
        ),
    ]
