# Generated by Django 5.0.5 on 2024-05-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0003_rename_tipos_tablas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tablas',
        ),
    ]
