# Generated by Django 5.0.5 on 2024-05-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0004_delete_tablas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaextra',
            name='comentario',
            field=models.CharField(max_length=500),
        ),
    ]
