# Generated by Django 5.0.5 on 2024-05-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0005_alter_personaextra_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaextra',
            name='comentario',
            field=models.CharField(max_length=1000),
        ),
    ]
