# Generated by Django 5.0.6 on 2024-06-08 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0006_alter_personaextra_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
