# Generated by Django 5.0.6 on 2024-06-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0014_alter_persona_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='imagen',
            new_name='foto',
        ),
    ]
