# Generated by Django 5.0.6 on 2024-06-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0015_rename_imagen_persona_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='orador',
            field=models.ForeignKey(limit_choices_to={'estado': 'Activo'}, on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.persona'),
        ),
    ]
