# Generated by Django 5.0.6 on 2024-06-12 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0016_alter_agenda_orador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='orador',
            field=models.ForeignKey(limit_choices_to={'estado_id': 1}, on_delete=django.db.models.deletion.CASCADE, to='bosquetaoista.persona'),
        ),
    ]
