# Generated by Django 5.0.6 on 2024-06-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0018_tabla'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabla',
            name='codigo',
            field=models.CharField(choices=[('DOCUMENTO', 'DOCUMENTO'), ('ESTADO', 'ESTADO'), ('EVENTO', 'EVENTO'), ('EXTRA', 'EXTRA')], default='DOCUMENTO', max_length=10),
        ),
    ]
