# Generated by Django 5.0.6 on 2024-06-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0019_tabla_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla',
            name='codigo',
        ),
    ]
