# Generated by Django 5.0.6 on 2024-06-13 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0021_tabla_codigo_tabla_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla',
        ),
    ]
