# Generated by Django 5.0.6 on 2024-06-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0022_delete_tabla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tabla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('TABLA', 'TABLA'), ('TIPODOC', 'TIPODOC'), ('TIPOCURSANTE', 'TIPOCURSANTE'), ('TIPOESTADO', 'TIPOESTADO'), ('TIPOEVENTO', 'TIPOEVENTO'), ('TIPOEXTRA', 'TIPOEXTRA'), ('CASA', 'CASA'), ('GRADO', 'GRADO')], max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
