# Generated by Django 5.0.6 on 2024-06-15 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0023_tabla'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tabla',
        ),
    ]
