# Generated by Django 5.0.6 on 2024-06-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0024_delete_tabla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
