# Generated by Django 5.0.6 on 2024-06-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0025_alter_persona_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frase', models.CharField(max_length=200)),
                ('detalle', models.CharField(max_length=200)),
            ],
        ),
    ]
