# Generated by Django 5.0.6 on 2024-06-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0026_frase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frase',
            name='detalle',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='frase',
            name='frase',
            field=models.CharField(max_length=500),
        ),
    ]
