# Generated by Django 3.2.25 on 2024-08-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0027_alter_frase_detalle_alter_frase_frase'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto2',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
