# Generated by Django 3.2.25 on 2024-08-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0028_persona_foto2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='foto',
        ),
    ]
