# Generated by Django 3.2.25 on 2024-08-22 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0029_remove_persona_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='foto2',
            new_name='foto',
        ),
    ]
