# Generated by Django 3.2.25 on 2024-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bosquetaoista', '0030_rename_foto2_persona_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='certificados/'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
